kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: nodejs
  SourceLocation: ./
  SourceType: local
  Application: app
  Project: wgordon
  Name: nodejs-zepe
  Url:
  - Name: nodejs-zepe-8080
    Port: 8080
